name: Node.js test CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container:
      image: node:20-buster-slim

    steps:
      - name: Checkout reps
        uses: actions/checkout@v3

      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm install

      - name: Run core tests
        run: npm run test:core

      - name: Run tools tests
        run: npm run test:tools
